### PR TITLE
fix: warn instead of reject when log directory missing at config time (#244)

### LINKED ISSUE #243: Bug: diskSpaceLimitUnit defaults to MB in Rust, but KB in Java
## Summary

The Rust v2 LogManager defaults `diskSpaceLimitUnit` to `MB` when not specified, while the Java LogManager defaults to `KB`. This is a 1024x difference in disk space limit interpretation for configs that omit the unit.

## Java behavior

When `diskSpaceLimitUnit` is empty, Java defaults to `KB`:

https://github.com/aws-greengrass/aws-greengrass-log-manager/blob/main/src/main/java/com/aws/greengrass/logmanager/LogManagerService.java#L268-L270

```java
if (StringUtils.isEmpty(diskSpaceLimitUnit)) {
    diskSpaceLimitUnit = "KB";
}
```

## Rust behavior

The Rust version defaults to `MB`:

https://github.com/aws-greengrass/aws-greengrass-log-manager/blob/rust/v2/src/config/schema.rs#L63-L67

```rust
impl Default for DiskSpaceLimitUnit {
    fn default() -> Self {
        Self::MB
    }
}
```

## Impact

A config like `{"diskSpaceLimit": "25"}` with no unit specified would be interpreted as:
- **Java**: 25 KB (25,600 bytes)
- **Rust**: 25 MB (26,214,400 bytes)

Customers migrating from the Java LogManager to the Rust version without changing their config would silently get a much larger disk space allowance.

## Suggested fix

Change the Rust default to `KB` to match Java:

```rust
impl Default for DiskSpaceLimitUnit {
    fn default() -> Self {
        Self::KB
    }
}
```

Introduced in PR #239.

### LINKED ISSUE #244: Bug: validate_directory rejects configs when log directory doesn't exist yet
## Summary

The Rust v2 LogManager validates that log directories exist at config load time. This can cause valid configs to be rejected if LogManager starts before the component whose logs it is configured to tail.

## Rust behavior

`validate_directory` checks `is_dir()` at startup and returns an error if the directory doesn't exist:

https://github.com/aws-greengrass/aws-greengrass-log-manager/blob/rust/v2/src/config/mod.rs#L55-L62

```rust
fn validate_directory(path: impl AsRef<Path>) -> Result<(), ConfigError> {
    let p = path.as_ref();
    if !p.is_dir() {
        return Err(ConfigError::Validation(format!(
            "Directory does not exist: {}",
            p.display()
        )));
    }
    Ok(())
}
```

This is called during `validate_config()` for every component and system log source.

## Java behavior

The Java LogManager does not validate directory existence at config load time. Instead, it handles missing directories gracefully at scan time — `LogFileGroup.create()` catches `InvalidLogGroupException` and logs a debug message:

https://github.com/aws-greengrass/aws-greengrass-log-manager/blob/main/src/main/java/com/aws/greengrass/logmanager/LogManagerService.java#L350-L355

```java
} catch (SecurityException e) {
    logger.atError().cause(e).log("Unable to get log files for {} from {}",
            componentName, componentLogConfiguration.getDirectoryPath());
} catch (InvalidLogGroupException e) {
    logger.atDebug().cause(e).log("Unable to read the directory");
}
```

## Impact

On a Greengrass device, components can start in any order. If LogManager starts before a component that creates its own log directory, the Rust version would reject the config and fail to monitor that component's logs — even though the directory will exist shortly.

## Suggested fix

Move directory existence checks from config validation to scan time, matching Java's behavior. Log a warning when a directory is missing and retry on the next scan cycle.

Introduced in PR #239.

### PR DESCRIPTION
**Pull request by paabbs**
## Fix

Log directories may not exist at config load time if LogManager starts before the component that creates its log directory. GG components can start in any order.

### Change

`validate_directory` now logs a warning and continues instead of returning an error. Directory existence is checked at scan time.

### Stacked on
- #245 (fix #243 — diskSpaceLimit defaults)

### Tests
111 tests, 0 failures

Closes #244

### CODE REVIEW

File: src/config/mod.rs [hunk 1]
```diff
@@ -61,10 +61,9 @@ pub fn validate_config(config: &LogManagerConfig) -> Result<(), ConfigError> {
 fn validate_directory(path: impl AsRef<Path>) -> Result<(), ConfigError> {
     let p = path.as_ref();
     if !p.is_dir() {
-        return Err(ConfigError::Validation(format!(
-            "Directory does not exist: {}",
-            p.display()
-        )));
+        // Warn but don't reject — directory may not exist yet if LogManager starts
+        // before the component that creates it.
+        tracing::warn!(directory = %p.display(), "Configured directory does not exist yet, will retry at scan time");
```
Comment (limingyaoo) [inline src/config/mod.rs]: We're saying "will retry at scan time" but that logic seems to be missing in the current change.

**Review by alter-mage — APPROVED** [review]

**Review by limingyaoo — APPROVED** [review]
