### PR TITLE
fix: use BufferedReader to read log files efficiently

### LINKED ISSUE #72: (CloudWatchAttemptLogsProcessor): ineffective file reading byte-by-byte
**Describe the bug**
RandomAccessFile::readLine() actually read file byte-by-byte which is ugly wasteful.
See https://docs.oracle.com/javase/7/docs/api/java/io/RandomAccessFile.html#readLine()
I observe 100% load on 2 of 4 CPU cores.

**To Reproduce**
Just log 100 lines per second from your component or stop greengrass, create 10-20 big log files and start greengrass again. Using htop and strace -p PID  observe system calls.

**Expected behavior**
Usage of buffer at least 4k in size is expected.

**Actual behavior**
Nucleus thread eat to much CPU when read the log files.

**Environment**
 - Ubuntu 20.04
 - JDK version: 11.0.11+9-Ubuntu-0ubuntu2.20.04
 - Nucleus version: 2.5.0
 - Log Manager version:   2.2.1

**Additional context**
Impact: system load

### PR DESCRIPTION
**Pull request by MikeDombo**
**Issue #, if available:**
Attempt to fix #72 

**Description of changes:**

Use a custom override of `BufferedReader` to buffer the log file contents in order to read more IO efficiently than `RandomAccessFile`. Needed to implement it the way that I have so that we can still know how many bytes we've read and then seek to that point in the file. 

**Why is this change necessary:**

**How was this change tested:**

**Any additional information or context required to review the change:**

**Checklist:**
 - [ ] Updated the README if applicable
 - [ ] Updated or added new unit tests
 - [ ] Updated or added new integration tests
 - [ ] Updated or added new end-to-end tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: src/main/java/com/aws/greengrass/logmanager/PositionTrackingBufferedReader.java [hunk 1]
```diff
@@ -0,0 +1,496 @@
...
+     *
+     * @return     A String containing the contents of the line, not including
+     *             any line-termination characters, or null if the end of the
+     *             stream has been reached
+     *
+     * @see        java.io.LineNumberReader#readLine()
+     *
+     * @exception  IOException  If an I/O error occurs
+     */
+    String readLine(boolean ignoreLF) throws IOException {
```
Comment (MikeDombo) [inline src/main/java/com/aws/greengrass/logmanager/PositionTrackingBufferedReader.java:261]: Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this method is 16. By comparison, 99% of the methods in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the method has a high number of decisions and it can make the logic difficult to understand and test. We recommend that you simplify this method or break it into multiple methods.

File: src/main/java/com/aws/greengrass/logmanager/PositionTrackingBufferedReader.java [hunk 2]
```diff
@@ -0,0 +1,219 @@
...
+                /* Skip a leftover '\n', if necessary */
+                if (omitLF && (cb[nextChar] == '\n')) {
+                    nextChar++;
+                }
+                skipLF = false;
+                omitLF = false;
+
+                for (i = nextChar; i < nChars; i++) {
+                    c = cb[i];
+                    position++;
```
Comment (rbattle) [inline src/main/java/com/aws/greengrass/logmanager/PositionTrackingBufferedReader.java:138]: can you add a comment here and on line 159 that this is what you added

File: src/main/java/com/aws/greengrass/logmanager/PositionTrackingBufferedReader.java [hunk 3]
```diff
@@ -0,0 +1,219 @@
...
+        }
+    }
+
+    public long position() {
+        return position;
+    }
+
+    public void setInitialPosition(long startPosition) {
+        position = startPosition;
+    }
```
Comment (rbattle) [inline src/main/java/com/aws/greengrass/logmanager/PositionTrackingBufferedReader.java:218]: comment that this does not jump to that position, but is only for tracking

**Review by rbattle — COMMENTED** [review]
small nits

**Review by philcali — APPROVED** [review]

**Review by nikkhilmuthye — APPROVED** [review]
